sudo: required
services:
  - docker

before_install:
  - docker build -t luislaborde/docker-react-frontend -f Dockerfile.dev . 

script:
  - docker run luislaborde/docker-react-frontend npm run test -- --coverage
  